### ISSUE TITLE
Report feature

### ISSUE THREAD

**Issue by Zynfu** [Xeio/WanderLost#1]
Hey, people troll the site and there is currently no feature to downvote or report a false location/card/rapport item.

**Comment by Xeio** [comment]
Yeah, it's something I'd like to address, haven't had a ton of time since I wanted to fix some of the problems with the site being slow first.

**Comment by Zynfu** [comment]
No problem mate. Btw absolutely love your site. Thanks a lot. Made keeping track so much easier

**Comment by Masterhpike** [comment]
I don't think it's a trolling thing, it was probably me putting in the wrong stuff because of daylight savings, the site for me is an hour behind so I have to add an hour every time. Took me few hours to figure out because steam didn't know what the issue was.

**Comment by Xeio** [comment]
Preliminary version of something to handle this is now merged as part of #8 and #10 .

**Comment by UnleashedMySelf** [comment]
> Preliminary version of something to handle this is now merged as part of #8 and #10 .

THX !!!!!!! :)
