### ISSUE TITLE
Data migration error after update the latest commits.

### ISSUE THREAD

**Issue by MagicPro1994** [Xeio/WanderLost#105]
Hello, I tried to pull your latest commits today. I got this message when trying to start the application.
![image](https://user-images.githubusercontent.com/8509065/169744224-d2723309-ba83-4136-b09c-501142ed10f5.png)

**Comment by Xeio** [comment]
Ah, yeah that's probably my bad, I ran the migrations in commit-order which works, but I don't think the code will do that. I probably shouldn't have made it two different DB contexts to begin with.

You can just comment out the data migration lines here:
https://github.com/Xeio/WanderLost/blob/3110191e088763d186628d64d6b4ea6ad814735e/WanderLost/WanderLost/Server/Migrations/AuthDb/20220519010947_BansOnUserTable.cs#L19

I should probably go back and just remove that.

**Comment by MagicPro1994** [comment]
Ok, it works now.
