### ISSUE TITLE
Arthetine - Warbringer Hills mouseover image URL is broken

### ISSUE THREAD

**Issue by michaelawill** [Xeio/WanderLost#110]
The mouse over image URL is set to: "https://lostmerchants.com/images/zones/Windbringer%20Hills.jpg"
But the current image location is: "https://lostmerchants.com/images/zones/Windbringer%20Hill.jpg"

**Comment by Xeio** [comment]
Oops, should have remembered that since it's not the first zone typo I had to fix. 🙃
