### ISSUE TITLE
Different PCs with same IP - voting duplication

### ISSUE THREAD

**Issue by pwojewodzic** [Xeio/WanderLost#115]
Hi, I'm playing with my girlfriend on two different PCs with same public IP and we investigated that our votes aren't unique. After discover some merchant by us, the other has vote on this merchant, same with earlier discovered merchant.

It's possible to fix it and make our PCs unique?

**Comment by Xeio** [comment]
Hmmm, possibly could make this account-based, if logged in. Would have to make some tweaks to the way it tracks votes behind the scenes though.

**Comment by pwojewodzic** [comment]
> Hmmm, possibly could make this account-based, if logged in. Would have to make some tweaks to the way it tracks votes behind the scenes though.

We're both logged in into our discord accounts.

**Comment by Xeio** [comment]
Should in theory allow tracking votes by account as long as you're each logged in. May act a little wonky if one of you is ever logged out, but basically similar to the old behavior of matching by IP.
