### ISSUE TITLE
no issue - fea. req.

### ISSUE THREAD

**Issue by lundakj** [Xeio/WanderLost#119]
Hi,
thx for yours work, this is really helpfull.
One idea - check box "done" for active traders can be helpfull...

**Comment by Xeio** [comment]
Generally speaking, you should be using the upvotes/downvotes for this.

**Comment by lundakj** [comment]
Or own memory, I know :). Up/Down does not exactly solve user memmory issue (others change count), but I really understand why you close it. But second, private Up/Down control will solve it.

**Comment by Xeio** [comment]
Not sure I understand, you should only vote on a merchant once you visit it right? And the button turns red/green once you vote.

**Comment by lundakj** [comment]
Ok, sorry. You are absolutly right. I vote only in cases that something is wrong, so I nave no idea, that tumb goes green by upvote. This is really solution of my memory problem + social benefit. So I am really sorry. And woting next time :).
Again, thx for yours GREAT work!
