### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by SpunksPoison** [Xeio/WanderLost#127]
Was logged in fine through discord authentification. Had to reload windows. I can no longer log in. I just get the message:
There was an error trying to log you in: 'Network Error'

Tried multiple times a day over the last week, whenever I found a combination I couldn't post without being logged in, and whenever I opened the page. Finally tried went to discord and removed the integration. Same message. Deleted all of my internet cache/cookies as a last resort. Still same issue.

Feel bad because I use the site a lot, and it was awful to see one unreported when I knew it was there.

**Comment by Xeio** [comment]
Hmm, so a network error implies that some request isn't making it to my server, though if you can access the rest of the site I'm not sure what it could be. I'm not seeing anything logged on the server, but that probably makes sense if it's a network issue. Do you get the error immediately when you click "login" or after you get redirected back from Discord?

If you want to poke at it a bit, you could look in the F12 dev tool menu the "Network" tab and see which of the requests are shown red when you refresh the site and try to login.

**Comment by SpunksPoison** [comment]
Immediately. It never goes to discord. I'll take a look at the dev tool.

**Comment by SpunksPoison** [comment]
Access to XMLHttpRequest at 'https://lostmerchants.com/.well-known/openid-configuration' from origin 'https://wanderlost.xeio.synology.me' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
lostmerchants.com/.well-known/openid-configuration:1          Failed to load resource: net::ERR_FAILED
blazor.webassembly.js:1 info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
wanderlost.xeio.synology.me/:1 Access to XMLHttpRequest at 'https://lostmerchants.com/.well-known/openid-configuration' from origin 'https://wanderlost.xeio.synology.me' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
lostmerchants.com/.well-known/openid-configuration:1          Failed to load resource: net::ERR_FAILED
/Authentication/login:1 Access to XMLHttpRequest at 'https://lostmerchants.com/.well-known/openid-configuration' from origin 'https://wanderlost.xeio.synology.me' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
AuthenticationService.js:2          GET https://lostmerchants.com/.well-known/openid-configuration net::ERR_FAILED 200
(anonymous) @ AuthenticationService.js:2
t.getJson @ AuthenticationService.js:2
t.getMetadata @ AuthenticationService.js:2
t._getMetadataProperty @ AuthenticationService.js:2
t.getAuthorizationEndpoint @ AuthenticationService.js:2
t.createSigninRequest @ AuthenticationService.js:2
(anonymous) @ AuthenticationService.js:2
Promise.then (async)
e._signinStart @ AuthenticationService.js:2
e._signin @ AuthenticationService.js:2
e._signinSilentIframe @ AuthenticationService.js:2
(anonymous) @ AuthenticationService.js:2
Promise.then (async)
e.signinSilent @ AuthenticationService.js:2
signIn @ AuthenticationService.js:2
await in signIn (async)
signIn @ AuthenticationService.js:2
(anonymous) @ blazor.webassembly.js:1
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
St @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.6.qf0o33bvyp.js:1
$func219 @ 00971e46:0x1a490
$func167 @ 00971e46:0xce5e
$func166 @ 00971e46:0xbd71
$func2812 @ 00971e46:0xabf01
$func1616 @ 00971e46:0x6fcc2
$func1614 @ 00971e46:0x6fc34
$func967 @ 00971e46:0x50685
$func219 @ 00971e46:0x1a449
$func167 @ 00971e46:0xce5e
$func166 @ 00971e46:0xbd71
$func2812 @ 00971e46:0xabf01
$func1616 @ 00971e46:0x6fcc2
$func1620 @ 00971e46:0x7032f
$mono_wasm_invoke_method @ 00971e46:0x969d
Module._mono_wasm_invoke_method @ dotnet.6.0.6.qf0o33bvyp.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet:19
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
b @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
ve @ blazor.webassembly.js:1
we @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
onGlobalEvent @ blazor.webassembly.js:1
/Authentication/login:1 Access to XMLHttpRequest at 'https://lostmerchants.com/.well-known/openid-configuration' from origin 'https://wanderlost.xeio.synology.me' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
AuthenticationService.js:2          GET https://lostmerchants.com/.well-known/openid-configuration net::ERR_FAILED 200

**Comment by Xeio** [comment]
Ah, you need to update your bookmark to https://lostmerchants.com
Should stop you getting the security warnings too. 😅

**Comment by SpunksPoison** [comment]
BTW, Amazing work. You deserve all the cookies. I've watched this grow from only a couple of people submitting things to what it is today. The best Lost Ark resource. Thank you for all the work that has been put into this.

**Comment by Xeio** [comment]
Yeah, I didn't want to juggle the SSL cert for the old URL so it was mostly decommissioned. It just happens to still work apparently... I should probably add an insecure redirect back there. Will still trigger a warning but at least everyone gets forcibly moved to the correct URL.
