### ISSUE TITLE
Sign-In with Discord

### ISSUE THREAD

**Issue by steel-raven** [Xeio/WanderLost#130]
Hi there. 

I'm kinda sorry, but I can't figure out what the discord sign-in is for. I did it and kinda nothing changed. 
I've thought you are doing that for more authentification against trolls. 
But even if I'm not logged in I can submit merchants and do up and down votes. 

Thanks in advance.

**Comment by Xeio** [comment]
You can vote and submit common items without authenticating.

You are required to log in to submit rare things like Legendary items (Rapport or Wei cards).

Also, it does actually track your submissions behind the scenes if you're logged in. If you click your user ID at the top right, it'll show a profile page counting your submissions. Wanted to do a leaderboard at some point, but been kinda lazy lately.
