### ISSUE TITLE
Feature request: sound volume control

### ISSUE THREAD

**Issue by Sakamoto0110** [Xeio/WanderLost#131]
Not sure if its possible but would be very nice if i could turn the volume down just a little bit

**Comment by Xeio** [comment]
There is a volume-control on the sound produced by the site on the Notification settings page. If it's your system notifications there's nothing I can do about those since they're controlled by Windows (or whatever other OS).

**Comment by Sakamoto0110** [comment]
holy, don't know how i never saw that option, thanks
