### ISSUE TITLE
Editing ApperanceTimes in data/merchants.json does not change spawntimes

### ISSUE THREAD

**Issue by Cyco0815** [Xeio/WanderLost#14]
Tried changing various ApperanceTimes, but they don't seem to have any affect on the client side. I could not find the cause yet, so just letting you know.

I guess it's nothing major, as they shouldn't be changed in production anyway.

**Comment by Xeio** [comment]
It's probably your browser caching the file.

Also if you're trying to debug/look at something, I put in a debug-build-only merchant yesterday if you pull the latest code.

**Comment by Cyco0815** [comment]
Oops you're right..
Yeah I've seen the debug merchant, very helpful! Although in my case I needed to test some specific interactions, for that I needed more merchants. But it works now, thanks.
