### ISSUE TITLE
Feature Request: Merchant History

### ISSUE THREAD

**Issue by incertia** [Xeio/WanderLost#141]
This is probably too much to ask for a stateless server but it may be worth tracking each merchant's reported history so users can track stats like Wei card frequency on their server. Probably requires some sqlite or postgres server to work optimally but would be a cool feature.

**Comment by Xeio** [comment]
It's not actually stateless, it's all stored in a database. That's how the account and profile system can work.

**Comment by incertia** [comment]
seems like this was recently added a few days ago
