### ISSUE TITLE
Questions over development practices on test.lostmerchants.com

### ISSUE THREAD

**Issue by hanvo** [Xeio/WanderLost#142]
Hi, I have been using the example here https://github.com/Xeio/WanderLost/issues/75#issuecomment-1130934828 to test. But, I am not sure if I am doing this correctly as I have a couple questions.

```ts
import signalR from "@microsoft/signalr";

const connection = new signalR.HubConnectionBuilder()
  .withUrl("https://test.lostmerchants.com/MerchantHub")
  .withAutomaticReconnect()
  .build();

connection.keepAliveIntervalInMilliseconds = 4 * 60 * 1000;
connection.serverTimeoutInMilliseconds = 8 * 60 * 1000;

async function start() {
  try {
      await connection.start();
      await connection.invoke("SubscribeToServer", "Shandi");
      await connection.on("UpdateMerchantGroup", async (server) => {
      const merchants = await connection.invoke(
        "GetKnownActiveMerchantGroups",
        server
      )
      console.log(merchants)
      });
  } catch (err) {
      console.log(err);
      setTimeout(() => start(), 5000);
  }
};

connection.onclose(async () => {
  await start();
});

start();
```

1. I found that `withAutomaticReconnect()` doesn't seem to do what it says. So I had to wrap it in a `onclose()` is this how it's intended to use or is there a bug somewhere within the signalR lib? Without wrapping in that enclose the connection ends and I have to restart the script. 

2. I have this set this test to listen to the test server of SignalR and I wanted a bit quicker development cycle. Is this the [endpoint](https://github.com/Xeio/WanderLost/blob/ca3f603ce08aed0ee6b70da083c226eb90fe9846/WanderLost/WanderLost/Shared/Interfaces/IMerchantHubServer.cs#L12), that allows me to push messages as much as I want to this dev (without getting permanently banned from the site) or am I suppose to wait every 30 minutes? 

3. I may be misunderstanding how this pub sub system works. But I am staring at the website and I am seeing that there should be messages: 
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/5769513/187050321-bc6a97a2-c766-4c23-b109-62ee3cae75b3.png">
But, it doesn't seem like any messages are being picked up on main server for Valtan. 

```ts
(node:20052) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[2022-08-27T22:33:50.494Z] Information: WebSocket connected to wss://lostmerchants.com/MerchantHub?id=zpJy-rGRAdLNQdoGwwpYgA.
```
Thanks for your time.

**Comment by Xeio** [comment]
For the most part as long as you're hitting the test site you can do whatever.

Generally, you would only get that "UpdateMerchantGroup" message when a new merchant is submitted. I do notice that in your code it subscribes to the "Shandie" server, but in the UI screenshot you're looking at the "Valtan" server. I'm not sure if that's your issue?

I can't really answer 1, that's more a SignalR question, I don't know if there's any specific oddities around the javascript library. I think someone else mentioned something around auto reconnect in another issue, but it seems fine to just retry manually with a delay like you are if that works.

**Comment by hanvo** [comment]
> Generally, you would only get that "UpdateMerchantGroup" message when a new merchant is submitted. I do notice that in your code it subscribes to the "Shandie" server, but in the UI screenshot you're looking at the "Valtan" server. I'm not sure if that's your issue?


Oh yea at the time Shandi didn't have anyone submit any reports so I swapped both my code and the website to show Valtan since someone had published a message there just for a screenshot. But I still can't seem to be messages regardless of what server I am on.


> I can't really answer 1, that's more a SignalR question, I don't know if there's any specific oddities around the javascript library. I think someone else mentioned something around auto reconnect in another issue, but it seems fine to just retry manually with a delay like you are if that works.

Okay no problem. I think I can leave it as it for now.

**Comment by Xeio** [comment]
Not sure, the code I prototyped that you linked seemed to work when I limitedly tried it. Just to be clear, you're starting up your client, _then_ going to the test site and submitting a merchant on the same server? The way your code is written it won't get merchants that were already submitted before it starts up and has to be running when the submission happens.

**Comment by hanvo** [comment]
Oh. I think that's probably where I am going wrong in this implementation. 

Is there a way to start up the client and get any active merchants at any point?

**Comment by Xeio** [comment]
You'd need to invoke the GetKnownActiveMerchantGroups call after the connection is successful.
