### ISSUE TITLE
Disconnection from server Error

### ISSUE THREAD

**Issue by thu2468** [Xeio/WanderLost#150]
Im getting 
![image](https://user-images.githubusercontent.com/1341488/192148100-c817cb9e-a06a-4654-9fc0-25ac16f303df.png)

**Comment by derp998** [comment]
Same here as well

**Comment by Chris2011931** [comment]
I have the same issue

**Comment by Xeio** [comment]
Serevr hit some unexpected data while fully processing the leaderboard. Should be fixed and back online now (you likely need to refresh the browser)
