### ISSUE TITLE
My name disappeared from the Armen leaderboard after Server merges

### ISSUE THREAD

**Issue by Sprachlos00** [Xeio/WanderLost#154]

**Comment by Xeio** [comment]
I'd need to know at least your display name.

Generally, to show up on the new server you need to submit at least one merchant there. There's some logic that will kick in to try and ignore the old servers that got merged away when determining the server you play on.

On your profile page it should show you which server the site thinks you've submitted the most to which is the server-specific leaderboard you will appear on.

**Comment by Sprachlos00** [comment]
Ty for the quick response, my display name is Yahikokonan and I used to play on Sirius and am now on Armen. As it seems I should be about rank 7 with my total submissions atm

**Comment by Xeio** [comment]
Looks like you just submitted your first on that server, so it will probably correct itself in the next half hour or so. Leaderboards only recalculate server and submissions after a new submission happens, after the merchant expires.
