### ISSUE TITLE
Navbar bug

### ISSUE THREAD

**Issue by Negri234279** [Xeio/WanderLost#155]
BUG -  When you open a dropdown in the navigation menu such as notifications or statistics, the menu remains displayed when navigating to another page such as about or merchants.

**Comment by Xeio** [comment]
Yeah, workaround is to just click the dropdown again and it will collapse.

There's a somewhat large UI overhaul likely coming in the near future from #151 which will probably tweak this.... at least when I actually clear clown and have some time to look at it.
