### ISSUE TITLE
Feature Request: Ability to toggle old text only view

### ISSUE THREAD

**Issue by ralinchan** [Xeio/WanderLost#156]
The new graphical view looks nice and i'm certain a lot of work was put into it but it is harder for me to quickly look at the information. Even more so if I try to bring up the site on my phone. Previously, I would be able to see almost every merchant on the screen but now, because of the size of the images, each merchant and the map location takes up the entire screen and i'd have to scroll down one merchant at a time.

**Comment by Nizqa** [comment]
I second this. The new cards take so much of the screen I have to look at the cards one at a time to see anything. Before you could only take a glance at the list and see. Really makes me wonder how this was thought as an improvement.

**Comment by ytzyt** [comment]
Or enable the cursor hover map view when we choose collapse card view.

**Comment by xMarkos** [comment]
The new view is a huge stepback.

1. It is not possible to see all items on my screen setup now and I have to alt+tab and scroll.
2. I have to focus too much to find the relevant information. The previous tabular form is much more suitable, because the information is always in the same place.

Unfortunately, since it is a blazor app, there is no easy way to tweak the UI myself.
I would very much welcome if there was a switch that could turn it back to the old form.

**Comment by Haran** [comment]
**Issues with new view:**
- Takes way more space on screen
- Doesn't allow to quickly see not yet submitted locations (opacity/dimming would help)
- Visual noise "steals" attention from finding what card/item exactly are available. 

Let's be honest, real lostmerchants value is quick and reliable information. Visual appeal is way less essential.

Please consider reddit thread https://www.reddit.com/r/lostarkgame/comments/xz5p34/looks_like_lostmerchanrts_changed_their_layout/ as part of this issue, because not every lostmerchants' user has github account to participate in discussion.

**Suggestion:**
I would suggest to implement radical UI/UX changes gradually and give users option to switch between old/new layout to see the percentage and how new layout is accepted by audience.

**Comment by xMarkos** [comment]
After a couple of hours using it, I have discovered more points that bother me.

1. The card color is completely meaningless (to me) as I want to buy all items anyway. The color should really represent what I have already cleared. The item inside the card has a color already so there is no point in having it duplicated in the whole card.
2. I have previously used the "thumb up" button to mark what I have already cleared. This information is now not visible at first glance. As mentioned in point 1, the color of the card should change with my upvote.
3. Although I already remember most of the spawn positions by heart, I still occasionally need a reminder. When the small cards view is used, this information is completely unavailable, which forces me to use the big cards all the time, just for the 1 case in 20 that I don't remember.

And a side note: My secondary monitor is in vertical orientation, and I used just a half of the screen for lost merchants. Now I have to use the whole screen to see it all, even in collapsed mode.

**Comment by ytzyt** [comment]
I think the most annoying part is still information being placed here and there not able to have a quick glance. I liked the previous layout way better.

**Comment by ph1f1** [comment]
Same here, don't like the new one. It's eye candy but not very clear to get the information quick. Would love to get an "opt-out" to the old layout.

**Comment by SSA-BlueKnight** [comment]
Unfortunately I have to agree with what others have stated.  I am sure a lot of work went into this, but the old layout was more useful/easier to use.

**Comment by Gettinglucky** [comment]
Please change it back to the previous format, I use fancy zones and it get split vertically to 1/2 of my screen, previously I was able to see everything when it was 1/2 my screen now it is 4 cards and I have to scroll to see and the cards are hard to quickly glance and determine what status of the merchants are.

**Comment by AndyofBorg** [comment]
I just wanted to add, I really love and appreciate lostmerchants.com and use it every day. The new version is honestly so much harder to use for me. Could you please add a toggle to get the old version of the website back for those of us who want it? Pretty please? Thank you!!

**Comment by Boochuchu** [comment]
Thank you so much for the time/energy you put into this site. A toggle to view the old option would be incredible, it just takes up way to much real estate on my screen to view everything. Thank you again, 
 appreciate everything you do!!

**Comment by Aelphaeis** [comment]
I agree this request, I wanted to highlight the following [comment](https://github.com/Xeio/WanderLost/pull/151#issuecomment-1274540310) from the pull request introducing this change. 

> Yeah, I'll try to sketch something on the weekend for a compact view, as I assume that's the most contested point :)

So seems like it's already on their radar.

**Comment by Gallygator** [comment]
Could you give us the choice to go back to the previous view (text only) ? The new view is nice, but I find it less efficient...
Maybe you could at least add a filter to remove uninteresting combinaisons in order to lighten the view ?

**Comment by user1736** [comment]
Hey folks! Compact mode is almost here, so you can check out the details in 
https://github.com/Xeio/WanderLost/pull/162

<img width="305" alt="image" src="https://user-images.githubusercontent.com/5519411/196036462-7ad7f2df-87fb-4aec-8e72-c1459eaab85d.png">

PS: if there's any designers or other FE folks out there, we could really use your help :)

**Comment by oleksandr-didyk** [comment]
Furthermore, we added a dedicated issue to tracking the feedback for the new UI and some additional information on what is already addressed and still needs to be looked at -> https://github.com/Xeio/WanderLost/issues/163

Feel free to add any comments / suggestions you have to the linked issue. It helps us to keep it all in one place for better tracking + we will try to keep its description up-to-date whenever a new change / issue is introduced

**Comment by ytzyt** [comment]
> Hey folks! Compact mode is almost here, so you can check out the details in #162
> 
> <img alt="image" width="305" src="https://user-images.githubusercontent.com/5519411/196036462-7ad7f2df-87fb-4aec-8e72-c1459eaab85d.png">
> 
> PS: if there's any designers or other FE folks out there, we could really use your help :)

Thanks for the good news. I personally think spreadsheet/table view is the most efficient way of representing info.
The previous view served this purpose really well; it's just so easy to look at the corresponding column for location after spotting the item I've set to track at a quick glance.

The only thing I didn't like about the old view is when ppl submit fake info(or misclick) and even with tons downvote the wrong info still stays there occupying extra roles. Maybe like the location map we can make the fake info to display only when cursor  hover over for detail?
