### ISSUE TITLE
Feature Request: Frame color of adjustable for cards and rapports

### ISSUE THREAD

**Issue by Chris2011931** [Xeio/WanderLost#160]
It would be nice, if there whould be a possibility to have a setting, weather the frame color of the card frames are displayed in the submitted card color (green, blue, purple, orange) or in the rapport column (purple, orange). For example in my case, for me the rapports are more important than the cards. But at the moment with the new interface, it is not possible to see on the first look, wether it is a legendary rapport or not. Therefore it would be great if there is a setting to change this behavior.

**Comment by Xeio** [comment]
The border will be yellow if there a legendary Rapport. 

The only exception to this is a Wei card which will also show yellow, though they're rare enough that you can mostly ignore that.

If the border isn't yellow, then the Rapport is epic because all other Rapport items are epic.

**Comment by Chris2011931** [comment]
Thank you for the information, did not see it last time. Then it’s all right and I close the ticket.
