### ISSUE TITLE
Page not working, "An unhandled error has occurred"

### ISSUE THREAD

**Issue by Malestriker** [Xeio/WanderLost#170]
For past 2 days page is not working for me, tried to clean cookies and change browser but it's not working.

**Comment by MilloshFey** [comment]
Yeah, me too. Getting this error:
![image](https://user-images.githubusercontent.com/46675702/203319220-a86d464a-fd23-4c97-a27a-bb7288a19052.png)

**Comment by leandrocouto** [comment]
I too am having this problem since yesterday.

**Comment by Xeio** [comment]
@MilloshFey If you're familiar with those dev tools, any chance you can check the Network tab and tell me why the websocket connection request failed?

Certificate should be good till January, and I seem to be able to connect from both my home network and from 4G. Possibly something is blocking it (Antivirus? ISP? Browser blocking extension?).

**Comment by leandrocouto** [comment]
I am not very familiar with web stuff but my 2 cents on this issue (network tab attached). I don't think this is an Antivirus issue since I don't have any. Possibly not extension related either, I disabled all of them (and tried on an incognito window, same problem). It is possible for the ISP to be the culprit since both my desktop and mobile have this problem when connected to the same home network. It works fine on the same mobile device if I use 4G, though.

Let me know if you need more information!

![image](https://user-images.githubusercontent.com/24583872/203413175-b3c8d087-8781-4d35-9906-eedb83776ab2.png)

**Comment by leandrocouto** [comment]
I cannot say this for certain but, the problems for me started around the same time [this library update](https://github.com/Xeio/WanderLost/commit/2fedf84bf4be6f2441e0afd06d223225dfc10ff0) was committed. I'm not familiar with that package, but that may be the reason (or a huge coincidence).

**Comment by KaduMoy** [comment]
I'm also having the same problem.
And it started yesterday

**Comment by SegatoNeto** [comment]
I'm having the same problem. The page is not refresh.

**Comment by Xeio** [comment]
Hmmm, try again. I found a possible deployment issue with one of the upgrades I did last week, though I don't really think it should be related to the error y'all are seeing it's possible it may have resolved it.

**Comment by KaduMoy** [comment]
Same mistake

<img width="1338" alt="Captura de tela_20221122_183142" src="https://user-images.githubusercontent.com/118855444/203425754-41a07eb3-d7a9-4afb-8160-fbd6d4428b18.png">

**Comment by Xeio** [comment]
Well, that's unfortunate though not unexpected. You could try connecting directly to https://hub.lostmerchants.com:15555/MerchantHub

You should get a mostly blank page that says "Connection ID Required" but if the ISP is blocking it maybe it'll spit out a more helpful message or something about a block.

I recall Verizon a while back really didn't like my site for whatever reason and would spit out a block that would have to be bypassed on initial load.

**Comment by KaduMoy** [comment]
I do not have access
Is it danda blocking the region?
I'm in Brazil
<img width="638" alt="image" src="https://user-images.githubusercontent.com/118855444/203427141-928ac78b-bd56-41b2-8e4f-bfb06708ca88.png">

**Comment by Malestriker** [comment]
I don't have access too

**Comment by Xeio** [comment]
I tried tweaking some networking settings on my end so you could try one more time, but since I didn't change anything network related in the last few days I'm not sure I can fix whatever is happening.

**Comment by KarymidoN** [comment]
Having the same issue.
![image](https://user-images.githubusercontent.com/10165677/203436004-a666bd47-8f13-4ded-916c-b86d38960829.png)
![image](https://user-images.githubusercontent.com/10165677/203436066-b9746213-6e53-45c0-ad92-13818c2b69ef.png)
Started today. tryed switching browsers, running on a VM, same error.

**Comment by KaduMoy** [comment]
at the address lostmerchants.com is ok
Now I can't get to hub.lostmerchants.com.

<img width="469" alt="Captura de tela_20221122_201923" src="https://user-images.githubusercontent.com/118855444/203440885-1a6e5ecd-e121-478a-9538-83dcdd4b5ad0.png">

**Comment by MilloshFey** [comment]
I dont know if its helpfull but https://hub.lostmerchants.com:15555/MerchantHub return "Connection ID Required" with error 400. Thats bad request, maybe something about certificade or headers? idk

![image](https://user-images.githubusercontent.com/46675702/203465397-d7894e7c-64e3-48fc-82ec-c1483a91d35a.png)

**Comment by MilloshFey** [comment]
Hey! Its working now :)
![image](https://user-images.githubusercontent.com/46675702/203465658-22cbebd6-a1ec-4cae-b9ca-8d7ae8f7239c.png)

**Comment by Xeio** [comment]
Mmm, maybe just got unlucky with some bad routing data cached somewhere in the pipe or some overaggressive firewall kicking in I don't control. Or someone cut a cable somewhere (wouldn't be the first time).

Something something internet, something sometthing series of tubes.

**Comment by KarymidoN** [comment]
now its working again thx :)

**Comment by Malestriker** [comment]
Yep, it's working, thanks!
