### ISSUE TITLE
Continent/Region/Island column and sort

### ISSUE THREAD

**Issue by ein1x3x** [Xeio/WanderLost#175]
Is it possible to add continent column to table and sort it according to it? To make it easier going trough merchants. I have 7 chars and i just put one on each continent to make it faster to go trough merchants on each one.

**Comment by apricop** [comment]
Compact mode for merchant grid (settings) specifies the continent. And it's a lot easier to follow. Hovering over locations when submitting or clicking on those posted pop-ups the map.
