### ISSUE TITLE
Burt not showing up as a possibility for the 8:30 spawn

### ISSUE THREAD

**Issue by davidroot8** [Xeio/WanderLost#182]
Burt from East Luterra only appears in the upcoming merchants for 9:30, even though he also spawns at 8:30.

**Comment by Xeio** [comment]
The data file seems correct.

https://github.com/Xeio/WanderLost/blob/92ee8e3ce60f813f04fd3b685ba9e6bfd385ce7c/WanderLost/WanderLost/Client/wwwroot/data/merchants.json#L342-L345

Are you saying you see Malone/Oliver/Nox and the other merchants that also spawn at the same time but not Burt?
