### ISSUE TITLE
Adjust to DST

### ISSUE THREAD

**Issue by Flipsoul** [Xeio/WanderLost#183]
It seems the website has not been updated to align with the NA and SA adjustments to DST.  People are unable to find the merchants at the listed times.

**Comment by Rootkit-** [comment]
Yep

**Comment by Xeio** [comment]
Should be fixed now, though maybe I should look into putting some of my original DST code back in if SG/AGS has actually fixed it permanently to auto-switch.

**Comment by Flipsoul** [comment]
ty for the quick fix! i mostly put this up just in case you, i can close this if you're cool.
Or, i could leave open if you wanted to track putting your DST code back in.

**Comment by GustinhoC** [comment]
Still not working for SA - Server Blackfang.

**Comment by Xeio** [comment]
Hmmm, did SA actually change? Back in November it didn't swap when NAE and NAW did, so I'm thinking it probably just wasn't wrong until the "fix".

**Comment by Xeio** [comment]
I reverted SA back to what it was prior to today's "fix". May need to refresh the page and let me know if there are still timer issues in that region.
