### ISSUE TITLE
"An unhandled error has occurred. Reload" bug

### ISSUE THREAD

**Issue by mokomel** [Xeio/WanderLost#185]
Have not been able to report or see any wandering merchants since ~4:10pm EST on March 25, 2023 on Chrome and Edge. It says, "Disconnected from server. [Try to Reload.]" and "An unhandled error has occurred. Reload." Wei Stats and the Leaderboard are also showing up as blank.

![Lost Merchants Bug](https://user-images.githubusercontent.com/25993634/227742118-2304435b-8c13-4c3b-9455-12af04750a27.png)

**Comment by Xeio** [comment]
Ah, unfortunately had a bit of a storm that knocked out power for a few hours, my UPS only lasts so long, and then the containers appear to not have started back up when power returned...

Should be good now.

**Comment by mokomel** [comment]
Oh no, hope you're alright! Thanks for the quick update. Stay safe!
