### ISSUE TITLE
Merchant Ben has new item?

### ISSUE THREAD

**Issue by ytzyt** [Xeio/WanderLost#187]
![_ Z_S$24@Q075LV 5O_J@67](https://user-images.githubusercontent.com/9277616/227809890-daa5bac2-3e30-435a-98e4-82045b326098.png)
![9RFUF9W12NMWLU5R{NW%WQG](https://user-images.githubusercontent.com/9277616/227809896-094d41e0-d084-4499-b6ea-39c38905cbcd.png)

Seems the legendary item is different

**Comment by Xeio** [comment]
Ah, so actually it's the same (image and all), though I think they may have renamed it while back. I should probably update it to match the localization change when I have time, but until then feel free to pick it since the merchants only have one valid legendary item anyway.

**Comment by Xeio** [comment]
Should be fixed now.
