### ISSUE TITLE
Punika Wandering Merchant - Missing Option 

### ISSUE THREAD

**Issue by maviscass** [Xeio/WanderLost#192]
The Punika merchant is missing one of the new item from the available list. 
Secret Pouch: Mysterious Green Pouch
![image](https://github.com/Xeio/WanderLost/assets/104755792/cfc3857f-d1a9-465c-ab61-249aefa0800c)

![image](https://github.com/Xeio/WanderLost/assets/104755792/7d9b575c-5d3c-4b10-ad2e-a13a99c290d8)

**Comment by Xeio** [comment]
Ah, so that one technically is always there... though it looks like one of the other two aren't guaranteed to spawn. I wasn't sure about that one reading the patch notes but every time I checked it always had a non-green bag.

**Comment by Xeio** [comment]
There should now be an option for this situation with only one bag for Rayni.

**Comment by maviscass** [comment]
Oh understood! 
Thanks for just adding that option so others may not be confused by it too!
