### ISSUE TITLE
Elgacia

### ISSUE THREAD

**Issue by Nevetso** [Xeio/WanderLost#196]
Hello, i've been using the website for a bery long time now, first time i come on gifthub, i'm just wondering if u will add "Vairgrys" stats like u did for "Wei" stats :D 

Thanks for your work, this website is amazing and life changer for everyone in Arkesia <3<3

**Comment by Xeio** [comment]
Yeah might be a good idea. I'd like to theoretically rework the card notifications to allow a bit of flexibility up to at least epic cards too though I've mostly been busy with other life stuff to do a lot more than maintenance on the site lately.
