### ISSUE TITLE
Delain Armen Nomination Does Not Exist

### ISSUE THREAD

**Issue by Wingkinken** [Xeio/WanderLost#204]
Delain Armen is not an option to select in East Luterra. This is very important as it is one of the main things people who haven't completed LWC are looking for now (me personally also).

Confused why there is an option to be notified, but no option to nominate it in the dashboard.

**Comment by Xeio** [comment]
I'm not sure what you mean by dashboard, it's available on the Morris merchant as well as in Push notification settings.

![image](https://github.com/Xeio/WanderLost/assets/25418/60df369d-a24b-4302-9295-99e8c4c56b79)
