### ISSUE TITLE
iOS Browser Notifications

### ISSUE THREAD

**Issue by mistaneat** [Xeio/WanderLost#206]
iOS now supports browser notifications:
https://www.xda-developers.com/how-enable-safari-notifications-iphone/
https://developer.apple.com/documentation/usernotifications/sending_web_push_notifications_in_web_apps_safari_and_other_browsers

You have to manually enable Push API in settings and add the app to the home screen for them to function, but looks like some site changes need to be made for them to work.

Not sure how much work is involved, but it would be awesome if this functionality could be added.

**Comment by Xeio** [comment]
Yeah, admittedly the biggest problem for me is I don't have any Mac/iOS devices to even try it, to know what kind of changes might need to be made for it to work. 😐

**Comment by mistaneat** [comment]
Yeah that makes it kinda hard without a device to test. Oh, I see you are adding discord PM notifications, that would also solve the iOS notification issue cause we can get notifications through discord.
