### ISSUE TITLE
Keep getting "Disconnected from server, automatically attempting to reconnect... Or you can try to reload."

### ISSUE THREAD

**Issue by Jefferson4096** [Xeio/WanderLost#208]
I keep getting disconnected and notifications aren't working anymore because of it, everything was working fine until a few days ago

**Comment by Xeio** [comment]
Out of curiosity is this Firefox? I saw something similar when I was testing something recently. but I wasn't sure what it was. It doesn't happen in other browsers so I sort of assumed it was my local dev environment.

**Comment by Jefferson4096** [comment]
Yep this was on Firefox, didn't try on other browsers. Also, it seems like it's working now, didn'get any disconnect this afternoon after opening the issue here

**Comment by Xeio** [comment]
I made a tweak to the keepalive intervals, should (probably?) make this go away. Dunno if that means Firefox made a change at some point recently since usually the client-only keepalive of 1-minute was previously working fine.
