### ISSUE TITLE
Discord bot notifications missing details

### ISSUE THREAD

**Issue by ann-one** [Xeio/WanderLost#209]
Thank you for adding Discord bot notifications! Can you possibly add location and card details into the text of the Discord bot notifications to match the format of the web push notifications? Right now the text body for each notification just says "Lost Merchants card notification" without any details, so it requires clicking through to the message in Discord to figure out which card and spawn location.

**Comment by Xeio** [comment]
Eh? It should look like this

![image](https://github.com/Xeio/WanderLost/assets/25418/bdf65886-a2a2-4562-89b9-36ff7e417cb4)

Both the desktop and mobile interfaces look like that for me (unless iOS behaves different than Android does?)

**Comment by ann-one** [comment]
I'm not talking about the text content of the Discord message, I specifically mean the text body of the Android system notification. I guess it would just be nice to simplify the way the text is formatted so that all the relevant information shows up in the body of the system notification for each bot message.

![image](https://github.com/Xeio/WanderLost/assets/140927380/fe493a78-60e3-4c83-852a-6b2ac1877cf7)

vs

![image](https://github.com/Xeio/WanderLost/assets/140927380/e9aacbc2-7faf-469f-9c10-4fd2e181837d)

**Comment by Xeio** [comment]
Ah, that's a bit trickier since Discord controls the formatting of the actual notification. Seems like it may just be puling from the text of the link header so I could change that.
