### ISSUE TITLE
Don't allow word-wrap on the table cells with the thumbs up and thumbs down icons

### ISSUE THREAD

**Issue by KOVIKO** [Xeio/WanderLost#22]
At some screen sizes, that table cell can get really weird. I'd highly recommend applying the `white-space: nowrap` CSS rule to those table cells.

![image](https://user-images.githubusercontent.com/835767/161828539-633d3137-0253-4244-b23b-1801797d712b.png)

**Comment by Xeio** [comment]
Honestly the whole thing needs redesigned. It was fine as a table when there were a few columns but the more that get shoved in the worse the layout gets at any screen width.
