### ISSUE TITLE
Submissions for Kayangel jump start server do nothing

### ISSUE THREAD

**Issue by vlczero** [Xeio/WanderLost#221]
When I submit a merchant for the Kayangel server I don't see it in the list. The list is always empty. I asked people in Area chat and others have the same problem. (almost missed a Balthorr spawn)

I am logged in with Discord. The server is not setup as my main server in the setting (just trying out jump start for a bit)

**Comment by Xeio** [comment]
Ah, I bet it's related to the "Jump Start" text on the server staus page. I do a check against that to make sure the region/server is online before allowing submissions...

I'll make to look at it tomorrow to be sure though.

**Comment by Xeio** [comment]
Should be working now hopefully.
