### ISSUE TITLE
North Kurzan merchant

### ISSUE THREAD

**Issue by adopeder** [Xeio/WanderLost#234]
There's a new continent, with its own merchant.

**Name**: Colvin

**Miscellaneous Items**
Root Tea - COMMON
Assar Mask - COMMON
Battle Rations - COMMON
Broken Doll - COMMON
Secret Pouch: Black Bait Pouch - EPIC
A Suspicious Map - EPIC
Fragmented Metal Shard - RARE

**Cards**
Agris - COMMON
Alcaone - COMMON
Tamut - RARE
Ren - EPIC

Not sure about his schedule, but I can say he's on right now, and the other merchats on are in RETHRAMIS / NORTH VERN / SOUTH VERN / ELGACIA / ROWEN / YORN

**Comment by Xeio** [comment]
Closed by #233
