### ISSUE TITLE
Project README Updates

### ISSUE THREAD

**Issue by mattycraig** [Xeio/WanderLost#27]
Hi there,

I'm a UI developer and I'd love to help contribute to this project. 

I was wondering if it's possible to get README instructions for running this locally for development? I've tried my best to run this but to no avail - I keep getting a persistent error issue when trying to preview in the browser so I must be missing something.

![Screenshot 2022-04-09 215650](https://user-images.githubusercontent.com/863364/162597940-e0345227-6c60-4bcf-a3bb-cf72859744bc.png)

Thank you!

**Comment by Xeio** [comment]
The browser should print a stack trace to the dev tools console whenever you see that error at the bottom of the page, given nothing loaded most likely some issue fetching the DLLs?

Generally speaking there shouldn't be much to setup if using Visual Studio. Assuming you are using the default (localdb)\MSSQLLocalDB database provider, you need to make sure to create a "wanderlost-dev" database inside it. The server will create the rest of the database schema automatically.

If you're using something else I'm not sure.

**Comment by Cyco0815** [comment]
Make sure to run the WanderLost.Server project, not WanderLost.Client.
![image](https://user-images.githubusercontent.com/101972110/162620189-bdc61480-b63f-4c9b-9686-a649fc33cd5f.png)

For me it just works, even created the database on its own without me having to manually set it up.

**Comment by mattycraig** [comment]
> Make sure to run the WanderLost.Server project, not WanderLost.Client. ![image](https://user-images.githubusercontent.com/101972110/162620189-bdc61480-b63f-4c9b-9686-a649fc33cd5f.png)
> 
> For me it just works, even created the database on its own without me having to manually set it up.

This worked for me! Thank you both so much for the replies.
