### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Niccolaus** [Xeio/WanderLost#32]
Right now I'm tracking Mac and Wei card, I also have notifications on Legendary Rapport items.
I do however only get the notification when Mac sells it, I'd like there to be a "All Legendary Rapport" notification which alerts me whenever any mechant sells one.

Also I'm a big fan of the website and it's helped me alot so far, thanks! 👍

**Comment by Xeio** [comment]
In addition to the "Notify when a Legendary rapport item is available" setting, make sure that this is checked next to each merchant you want to get rapport messages for (sounds like all of them in your case): 

![image](https://user-images.githubusercontent.com/25418/163472239-cc18cb47-e413-40bb-b5e6-3054eea0248e.png)

That enables/disables the merchant overall. They should all be enabled by default normally though...

**Comment by Niccolaus** [comment]
I have them turned off because I dont want a notification every time they spawn.
Thats the point, I want to get a notification when they sell legendary items but not when they spawn.

**Comment by Xeio** [comment]
Mmmm, so you want to be notified when the Wei merchant spawns, but not the others then?

**Comment by Niccolaus** [comment]
Yes correct, and on top of that whenever ANY merchant has a legendary rapport item :)

**Comment by Xeio** [comment]
This should now be live, just completely removed the enable setting per-merchant and adding a spawn setting to each merchant.

You'll probably have to reconfigure since it doesn't transfer the old spawning settings.
