### ISSUE TITLE
Feature Request - Specify the epic rapport gift being sold

### ISSUE THREAD

**Issue by AlantaRian** [Xeio/WanderLost#36]
In terms of silver costs, it's cheaper to use the 450 rapport gifts than legendary gifts (the same amount of silver gets you 80% more rapport). Thus it would be nice to have an ability to track specific epic gifts and get alerts about them.

**Comment by Lunariz** [comment]
+1 for this, exactly what I'm missing. I've finished 2 of the 3 rapport NPCs in Tortoyk, so right now only 1 in 3 visits actually gives me the item I want. Would save me a lot of time to know which item is there. Same thing for a lot of other continents.

**Comment by Sedro01** [comment]
@Xeio would you accept a PR for this?

**Comment by Xeio** [comment]
Yeah, honestly biggest headache is mostly the data entry in https://github.com/Xeio/WanderLost/blob/main/WanderLost/WanderLost/Client/wwwroot/data/merchants.json (Should be structured similar to cards, with a rarity + name), even if that's all you want to provide. Technically if you want to go further you could even add an "AdditionalText" field or something to use as a tooltip for which NPCs the Epic rapports are for though I'd need to make some small tweaks to the UI code to display it. 

As far as code I could do most of that if you don't want to/can't. It's basically the merchant validation, grid display, update merchant page, and the notification settings page. I'll probably try to put in a compatibility shim for the notifications settings too so it defaults anyone that had "Legendary" to select all the legendary items.

Also it's probably a client-breaking change, but I have the ability to force client page reloads so hopefully that part at least will go smoothly...

**Comment by Sedro01** [comment]
> I'll probably try to put in a compatibility shim for the notifications settings too so it defaults anyone that had "Legendary" to select all the legendary items.
Maybe I'll add notification support for individual rapport items in a separate PR

**Comment by Xeio** [comment]
Thanks for the PR, didn't mean to close this issue immediately...

I did add the notification logic, and it should migrate the old settings to the new as well. Will deploy it probably some time tonight.

**Comment by Xeio** [comment]
Now live, client should automatically refresh to latest.

**Comment by Cassock** [comment]
Excuse the necro and tell me if this should be a new issue or not, but appending the NPC that this epic item gives 450 rep for would be spectacular (so I don't have to memorize which gift goes to who). Maybe an icon or NPC name to the right of the item name, or icon/picture/name on mouseover?

**Comment by Xeio** [comment]
You would probably want to open a separate issue to track. It's possible, mostly the work of entering all the data (displaying it would be fairly simple).
