### ISSUE TITLE
Questions regarding notification.

### ISSUE THREAD

**Issue by LoveSOJU** [Xeio/WanderLost#38]

**Comment by Namgi97** [comment]
Hi team, I have one question. For me, it looks like the notification is working with sound and windows notification when I have the 'https://lostmerchants.com/' website opened but doesn't give me any notification if I did not open up the web site. Is this normal? Do you have to be on the website to receive the windows OS notification?

**Comment by Xeio** [comment]
Yes, everything currently functions via the browser tab, so you have to keep the site open in the background to function.
