### ISSUE TITLE
Notif Name + Location

### ISSUE THREAD

**Issue by Nanology101** [Xeio/WanderLost#39]
Notification Settings, adding the Location of the Merchant would be very useful. Dorella (Feiton) etc.

**Comment by Cyco0815** [comment]
To clarify, you want to see the general continent/region the merchant is in? 
Because the location should already be in there:
![image](https://user-images.githubusercontent.com/101972110/164079393-257a60a5-6332-4fd0-ba4f-6276b629f1a5.png)
