### ISSUE TITLE
Times are an hour off, at least for NA east

### ISSUE THREAD

**Issue by 32dee78da5d176bcba3366fc923e9a85** [Xeio/WanderLost#4]
Before the 3/17 maintenance it worked great, however now the merchants are showing up an hour before their "next appearance" time
![5XfqzcwOKa](https://user-images.githubusercontent.com/101891392/159055246-6c4ce20f-3fff-42ac-822e-f05b84da9f47.png)

**Comment by Xeio** [comment]
Of course, so they probably changed the UTC offsets of the servers. That would explain why everyone was mentioning breaking the server times ysterday which I didn't understand, hah.

Worst part is the client times are still broken so I don't even know what they're doing (and I don't think they do either).

I'll probably push an update at some point today, though I can't really guarantee it won't break again when they make yet another attempt to fix DST.

**Comment by Jaerin** [comment]
Well the timers/clock appear to be fixed in game as of this morning.  The display for the clock in the upper left has changed to not display AM/PM or Timezone anymore like it used too.  So who knows what they are doing.

**Comment by Rukongai** [comment]
+1 on this issue for NA-West as well.

**Comment by Xeio** [comment]
Should be fixed, note the browser cache may have stale values for a bit. Might want to temporarily try in Incognito/Private mode in your browser till the old values expire.
