### ISSUE TITLE
Misspelling - Eohl => Eolh

### ISSUE THREAD

**Issue by kyleshrader** [Xeio/WanderLost#42]
The card named Eolh is mispelled on the merchant page.

**Comment by Xeio** [comment]
Fixed, though may not be live till tomorrow

**Comment by kyleshrader** [comment]
Nice. By the way, if you switch to using branches and creating PRs... you can say Fixes #42 in the PR description and it links it to issues. There are other benefits too when you have multiple contributors, but I won't bother your process...
