### ISSUE TITLE
Are shadowbans a thing? Have I been shadowbanned or just unlucky?

### ISSUE THREAD

**Issue by wwartick** [Xeio/WanderLost#45]
Ok so I HAVE trolled Wei card ONCE (during 8-hour maintenance where noone was able to login) and now everytime I post a location it gets hard downvoted. after 5-10 minutes I see the same location/items put up and it gets upvoted and stays up. I get that the votes dont really matter big picture, but I'm rapport grinding rn, and frequently get to merchants before others, but can't share locations because of this. I get that I probably deserve this because Wei-trolls bad but I specifically picked a harmless time to do it and can't help others now. Is there a way to appeal this? If not I get it, oh well.

**Comment by Cyco0815** [comment]
Yes shadowbans are a thing. Depending on your offense the ban will be automatically lifted in a couple of weeks.
