### ISSUE TITLE
[Feature request] Notifcation System

### ISSUE THREAD

**Issue by stefan0uh** [Xeio/WanderLost#5]
# Idea: 
Adding a notification System, to get informed when a merchant of a selected server is available.

# Possible solutions:
* Usage of the browser push system
## Other options for custom clients (like discord bots)
* An open API which returns all information from the web socket
* Web socket with a second hub which is read-only from any URL

**Comment by Xeio** [comment]
Preliminary version of this is now deployed from #16 and #19.

There's still some work to be done to improve it, but it's a good first draft.

If you want some sort of socket endpoint that should probably be a separate issue, though technically speaking there's nothing stopping someone from using the current endpoints as read-only by just subscribing to events. Headache might be that I (and others doing pull requests) have been tweaking that API so it's not entirely stable. I forsee some potentially breaking changes in the future with handling votes and such.
