### ISSUE TITLE
Merchants timer is wrong

### ISSUE THREAD

**Issue by ANGOLANGOLA** [Xeio/WanderLost#50]
Hi there, after latest LA update there's a bug at least for EUW Tortoyk server. Website thinks all of the Merchants stay up for 25 seconds instead of ~22 minutes, so you can't inform other players about any of the merchants place and loot because before i feel everything up website skips to next Wandering Merchants waiting timers.

**Comment by Xeio** [comment]
Whoops, should be fixed for next spawn. Pushing test branch out bad. >_<
