### ISSUE TITLE
Feature Request - Checkbox Option

### ISSUE THREAD

**Issue by Prolly92** [Xeio/WanderLost#51]
It's a minor issue, but I'd like it if there was an option to check off whichever NPC we have visited for that timeslot. Just a simple checkbox/strikethrough feature would be great. Not really an issue when there's a handful of merchants up, but on some time slots I tend to get lost pretty easily while I'm trying to get as many as possible. With the discord bot you can open up every map as it pops up and close the tab after you get it so it's easy to keep track which ones are left. Anything that could help with this issue would be greatly appreciated, it's the one thing where I still prefer using the discord bot over this.

**Comment by Xeio** [comment]
As of late last week, when you up/downvote you can see which submissions you have voted on. If you upvote the ones you visit that could effectively be your checkbox.
