### ISSUE TITLE
Show optimal NPC for each Epic gift

### ISSUE THREAD

**Issue by Cassock** [Xeio/WanderLost#53]
Piggybacking on #36 

Appending the NPC that each epic item gives 450 rep for would be spectacular (so I don't have to memorize which gift goes to who). Maybe an icon or NPC name to the right of the item name, or icon/picture/name on mouseover?

**Comment by Cassock** [comment]
Alternatively, being able to turn off or gray out each item if I'm no longer interested in it would be great.

**Comment by EmreKLC414** [comment]
Yo! i made a gift list for my adventure tome rapports, you can copy and edit for ur self if you want.

https://docs.google.com/spreadsheets/d/1zWCHEh6tjYzBca5mcEAXI5hLhYyAt7wOe5kpoP8NBHI/

**Comment by Xeio** [comment]
Code support for this is live, though have to fill in the data at some point now since it's just Shana's so far:

https://github.com/Xeio/WanderLost/blob/main/WanderLost/WanderLost/Client/wwwroot/data/tooltips.json
