### ISSUE TITLE
Feature Request: Thumbs down 10+, remove entry

### ISSUE THREAD

**Issue by yourpals** [Xeio/WanderLost#54]
For the sake of keeping it clean and getting rid of trolls, I suggest entry gets deleted if it receives 10 thumbs down

**Comment by musthabe** [comment]
So trolls can just open 10 incognito pages and start deleting valid entries? This wouldn't work.

**Comment by Cyco0815** [comment]
The system is a bit more robust than that.. 😅 But I agree, removing entries outright could enable trolls.
Last nights update should help with clarity, downvoted merchants are now greyed out and the highest voted merchant is always on top.

**Comment by yourpals** [comment]
Didn't think of that with trolls, and I must say the new update is amazing! Thanks for the work
