### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by cosmosext** [Xeio/WanderLost#57]
'An unhandled error has occurred. Reload' at bottom of the page.

**Comment by Xeio** [comment]
Yeah, I think I ran into this one unfortunately caused by #56, working on a fix.

**Comment by Xeio** [comment]
In theory fix should be live, should be able to refresh the page.

I won't be 100% it's fixed until the next spawn times. Let me know if you're still seeing it.

**Comment by Xeio** [comment]
Also had a fun deployment issue apparently which is also now resolved...
