### ISSUE TITLE
Feature request - Top/Condensed Menu Bar

### ISSUE THREAD

**Issue by element73** [Xeio/WanderLost#60]
Allow us to minimize/hide the left blue menu. Takes up a lot of [unused space](https://prnt.sc/JO-N1l7a5MPO) on the desktop.

**Comment by Xeio** [comment]
Yeah, may actually end up shrinking this into a topbar menu, since some of the login stuff I'm working on fits better horizontally. That functionality is a bit rough right now though so could be a bit.
