### ISSUE TITLE
Ability to Deselect Thumbs Up/Thumbs Down instead of select the other

### ISSUE THREAD

**Issue by AsthmaQueen** [Xeio/WanderLost#65]
Issue: Sometimes I would click the wrong one to confirm but am unable to unselect it to nuetral and have to either vote it up or down at that point.

Solution: Change it so clicking Thumbs up or Thumbs down if already selected removes the vote for that merchant so you are not forced to select one or the other.

**Comment by Xeio** [comment]
Done
