### ISSUE TITLE
Wrong merchant timers on first visit

### ISSUE THREAD

**Issue by Cyco0815** [Xeio/WanderLost#66]
Merchant timers are wrong if the site is visited for the first time (no LocalStorage data in browser) and the server region is swapped before a server gets selected. The following GIF shows a demonstration with Chromes incognito mode.

In this, I first show the actual state for EUC Asta, afterwards I go to Incognito Mode to open the site again with no cookies/localstorage. I then select a "wrong" region, in this case NA East, then change it to EUC and select Asta server. Now the timers for the upcoming merchants seem to be messed up, I think it applies the wrong region timezone or something. Timers for the active merchants will be wrong aswell.
![ServerRegionBug](https://user-images.githubusercontent.com/101972110/165387877-f5281aca-dfd1-4d6a-a984-3bfd48718785.gif)

If the site is refreshed the timers will be correct again, as the LocalStorage is not initialized and the server region and server are saved.
I tried debugging it, but have not found anything yet.

**Comment by Xeio** [comment]
Might explain #50 

It looks like SynchronizeServer doesn't account for regional offset changing. Possibly more correct would be for the Region change to call UpdateMerchants with force=true (since it doesn't normally need to happen when server changes, or when re-synchrozing after a reconnect).

**Comment by Xeio** [comment]
Should be fix in the next deploy, though may be a day or two since I want to put some touches on the authorization piece first
