### ISSUE TITLE
Correct submissions keep getting downvoted

### ISSUE THREAD

**Issue by noname-notime** [Xeio/WanderLost#69]
I've submitted wandering merchant locations here and there but recently whenever I've submitted any, they would get downvoted quickly even though they're the correct location and items.  Then minutes later a new submission for the merchant will be created with the exact same listings as what I put but it won't get downvoted.  Example where I've submitted suggestions for Rethramis, West Luterra, and East Luterra, but they've all been downvoted except the non-downvoted one which I didn't submit remained fine even though the location and items are the same as what I inputted: https://i.imgur.com/IVIXY9U.png

This has happened on multiple spawn time occasions as well and it doesn't seem like it's a coincidence.  Another example: https://i.imgur.com/Ehpk8bI.png In this example I submitted all the submissions for Rethramis, West Luterra, and East Luterra but they were all downvoted once again.  I submitted again to those 3 regions but on my phone on mobile data and they did not get downvoted like the previous posts.

This is another submissions for Punika region: https://i.imgur.com/hsPcFp9.png

**Comment by wwartick** [comment]
I had the same issue, turn out shadowbans are a thing? Did you troll a Wei spawn? or get a spawn wrong? I put up Wei during maintenance 3(!!) weeks ago and still can't submit correct locations. idk the threshhold but yea I have the same issue.

**Comment by AsthmaQueen** [comment]
This is happening right now as well only on legendary rapports for Una Server - NA East.  As soon as Legendary Rapport is posted gets downvoted 10+ times very quickly

**Comment by noname-notime** [comment]
> I had the same issue, turn out shadowbans are a thing. Did you troll a Wei spawn? or get a spawn wrong? I put up Wei during maintenance 2 weeks ago and still can't submit correct locations. idk the threshhold but yea I have the same issue.

I've never trolled a Wei spawn.  Sometimes I get spawn items wrong from misclick but I always redo another submission right after if that happens.  I feel like the threshold for the shadow bans might be too low.
