### ISSUE TITLE
Discord Sign-in errors out when Discord Id contains Special Characters

### ISSUE THREAD

**Issue by mjoemar53** [Xeio/WanderLost#70]
Reproduction Steps;

1. Sign-in using Discord Login

I suspect that that name checking doesnt support special characters.
![image](https://user-images.githubusercontent.com/61579441/165872113-aa59a9f0-2ab1-41d5-8001-f0b1112b4ebb.png)

**Comment by Xeio** [comment]
Mmmmm, I probably can just disable that validation since those names aren't really used anyway.

**Comment by Xeio** [comment]
Should be fixed now, try again and let me know if you see any issues.
