### ISSUE TITLE
Highlight Merchants you submitted location for

### ISSUE THREAD

**Issue by mytelefe** [Xeio/WanderLost#71]
As of now you can mark the merchants you already visited by voting thumbs up/down and I think it is great but if you are the one that submitted merchant location first you of course cannot vote which means you cannot "tick off" merchants you found yourself.
I know it is a minor issue but it would be great if merchants you found first and cannot vote on would be marked with green thumbs up by default.

**Comment by Xeio** [comment]
It will now display a default upvote on your own submission (that doesn't count in the total votes).
