### ISSUE TITLE
Lay out preferences?

### ISSUE THREAD

**Issue by xsFluffy** [Xeio/WanderLost#72]
I'm not a fan of the new layout.
Having a big bar at the top of the page seems inconvenient.
Everything seems so extremely zoomed in right now.

Perhaps an option to move the bar back to the side or have it minimized. 
Would also be nice to alter the size of text and spaces inbetween.

**Comment by Xeio** [comment]
Probably not going to make this configurable since it's hard enough to get the layout agreeable without trying to make two layouts.

Might make it so you can scroll past the nav bar, rather than it being sticky though.
