### ISSUE TITLE
IPad - reload error when attempting to enable notifications

### ISSUE THREAD

**Issue by Jester2020** [Xeio/WanderLost#81]
1) Safari
2) click enable notifications 
3) page displays pink error reload bar at the bottom
![image](https://user-images.githubusercontent.com/105181072/167323956-a8eea623-5989-4d1a-a21c-b5aa5864c516.png)

**Comment by Jester2020** [comment]
No worries,

I figured it was probably an iOS issue.  Love the site, if any type of motivation is possible in the future cool if not I appreciate the reply 

Jesse

**Comment by Xeio** [comment]
You should be able to modify the settings now, probably the only way you can get notified is the "sound" setting though since that doesn't require any special permission.
