### ISSUE TITLE
We're 99.9% sure there's only one Croconys spawn point for Burt

### ISSUE THREAD

**Issue by KOVIKO** [Xeio/WanderLost#82]
Stating "(South)" in "Croconys Seashore (South)" appears to be extraneous. Not once since launch have I actually seen Burt in the purported northern position.

**Comment by Xeio** [comment]
Hmmm, yup just ran a query against all my accumulated data (at least since the site went live), never seen one upvoted for North.

Not sure where I pulled that from but I think some of the reference guides may be wrong then. 😅

**Comment by Xeio** [comment]
Also tracks partially back to #6
