### ISSUE TITLE
Unable to login with Discord

### ISSUE THREAD

**Issue by DavidSDP** [Xeio/WanderLost#84]
Hello, I tried to login with Discord for the first time and after pressing the Authorize button on the Discord Popup, a message appears: "Username 'dabicho#????' is already taken." 
![image](https://user-images.githubusercontent.com/11381136/167427368-9124e036-c56d-4603-a95f-b732b3d1f0f1.png)
This is the first time I attempt this, for sure. And I tried restarting PC and clearing cache and nothing seems to work.

**Comment by Xeio** [comment]
I purged the user, I think it may have been a slowness issue this morning caused by one of my backup tasks. Somehow when you logged in it created the user but didn't associate it with the discord identifier so there was no way to login to the account.

**Comment by Xeio** [comment]
Looks like you weren't the only one with this issue either, though I can't tell if they were all from today. Purged them all. Going to have to tweak that to be a little more graceful upon partial failures.

**Comment by DavidSDP** [comment]
It is working fine now, thank you. Amazing work you did with this app btw!
