### ISSUE TITLE
[ Feature request ] - Simple API for requesting the data

### ISSUE THREAD

**Issue by Sakamoto0110** [Xeio/WanderLost#89]
Hey, I wanted to make a simple python ( or even in c++ ) prorgam just to have a super lightweigth GUI to run in background for personal use, but i couldn't find a way to retrieve data so i think would be nice to have some API just to retrieve the data, for safety reasons, i don't think would be a good idea to allow submit locations

**Comment by mchangrh** [comment]
There's good references in #75 

with the siginalR connection you get instantaneous updates instead of requesting like a normal API

**Comment by Sakamoto0110** [comment]
thanks
