### ISSUE TITLE
merchant timer delay

### ISSUE THREAD

**Issue by Natsume150** [Xeio/WanderLost#90]
merchant timers are delayed for 3 mins for me, I don't know why, sometimes I hear favorite alert, I check the site but it still shows merchant will be up in 2 minutes or so, and website shows merchant is still up and 2-3 mins left while merchant has despawned in the game. I am using google chrome.

**Comment by Xeio** [comment]
Is your computer clock correct? Like in-game the merchants disappear at :55 after the hour? The browser should be calculating everything based on the clock from the operating system.

**Comment by Natsume150** [comment]
hi, I just realized my computer didn't synchronize the time, dunno why, I checked my phone there was a 3 minute difference, I fixed it now, thank you!
