### ISSUE TITLE
South Vern Epic Gifts Incorrect NPC Attribution

### ISSUE THREAD

**Issue by camclemons** [Xeio/WanderLost#95]
The current tooltips for the Feather Fan and Febre Potion are swapped with each other's correct NPC. The fan is Candaria Neria's favorite, and the potion is Thar's

**Comment by Xeio** [comment]
I'mma just blame #88 for this one since I couldn't yet access Thar before to check. The buck stops with somebody else!

May put that Charisma requirement in there too, 350 is... high.
