### ISSUE TITLE
Test notification is greyed out in notification settings.

### ISSUE THREAD

**Issue by Rhythmslc** [Xeio/WanderLost#96]
I use this setting a lot cause for some reason my machine likes to constantly change my focus assistant settings I haven't gotten a notification today I haven't seen a legendary on manually checks but I wanted to test notifications just top make sure and it's currently greyed out so right now I'm not sure if the site sending them or not. there is also a new push notifications area that says Failed to retrieve push token from browser service worker. when I go to it.

**Comment by Xeio** [comment]
For the normal Notifications page you need to make sure the "Use In-Browser Notifications" checkbox is enabled, if you want to use those test functions. This was tweaked slightly so it's possible to enable Sound vs Browser Notifications separately. In theory it should have defaulted to true if you already had notifications enabled prior to the update though.

As far as Push Notifications, you may need to be more specific about what operating system and browser you are using.

**Comment by Rhythmslc** [comment]
I'm on windows 10 using the Brave Browser. like I said though I'm not sure if something is wrong but the button used to work for testing system notifications. please don't remove a function I used a lot, like I said my focus assistant keeps resetting it's not a page issue but I use that function a lot and now it's disabled I appreciate adding more functionality but please keep the old button functionality or a new button. loosing the tool means I miss a lot more notification.

**Comment by Xeio** [comment]
It's not removed, the test button doesn't make any sense if you don't have browser notifications enabled, so you have to check the box before it will function.

**Comment by Rhythmslc** [comment]
I check it and I don't get a system notification.

**Comment by Rhythmslc** [comment]
I have completely redo my focus assistant but it's working now.

**Comment by Xeio** [comment]
Sounds like the browser for some reason is blocking all notifications. Nothing should functionally have changed if that setting is checked. 

You may want to try disabling then re-enable notifications from the browser (or set it back to "ask" so the browser will prompt you again on the page). In theory it would look something like this second question on the help page but I'm not familiar with brave. https://lostmerchants.com/NotificationsHelp

**Comment by Rhythmslc** [comment]
it wasn't the browser it's windows focus assistant I had to completely remove my browser for priority and readd it and reset it up. I actually tried disabling and enabling first but didn't get the prompt again.  I made some more changes so I hope it sticks this time.

**Comment by Xeio** [comment]
Yeah, the focus assist setting tends to be a problem in general and is largely the reason why the help page was created.
