### ISSUE TITLE
Need help on `FirebaseSecretFile`, Firebase not config

### ISSUE THREAD

**Issue by MagicPro1994** [Xeio/WanderLost#99]
I got this message when trying to setup and run the project. 
![image](https://user-images.githubusercontent.com/8509065/168960915-e9966121-d79c-4382-b2bc-dd92894202f4.png)

Can you help me to fix this problem?

**Comment by Xeio** [comment]
So, depending on if you actually want to test out push messages through FCM, you can ignore that.... though it will log that message every 20 seconds or so. If you don't have that configured, the rest of the site will work on local, just won't send push messages.


To actually set it up Firebase there's a bunch of steps, but mainly after creating an app you need to go to the project settings and get your client config

![ClientConfig](https://user-images.githubusercontent.com/25418/168961799-9f30bc11-d645-4df9-ac6d-e56773438a2c.png)

This will replace the "FirebaseDevConfig.js" file at the root of the server folder. Note you'll probably need to change "const" to "var" there as it just loads that "firebaseConfig" variable to the global window scope in javascript to be used by the ServiceWorker.

The steps for the secrets file are a bit more complicated you need to go to "Service Workers" in the settings and open the service accounts page.

![ServiceWorkers](https://user-images.githubusercontent.com/25418/168962094-a46833a0-5580-4508-b4fd-598476c6711c.png)

From there, you need to generate a new JSON key, and save that somewhere on your disk.

![Generate Key](https://user-images.githubusercontent.com/25418/168962771-2f011c40-8b07-48ab-bda0-dd62576ee117.png)

The last step is just adding the line to your secrets config file in Visual Studio, something like.

"FirebaseSecretFile": "C:\\\\path\\\\to\\\\secret\\\\firebase-secret.json"
